# -*- coding: utf-8 -*-
"""alexNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pe-v-t55FFvpY6wZXe2KAVwCLSOBgsq
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import wandb
import os

wandb.init(project='alexnet-flowers-v2', config={
    "epochs": 10,
    "batch_size": 16,
    "learning_rate": 0.001,
    "architecture": "alexnet",
    "pretrained": True,
    "input_size": 128
})

config = wandb.config

transform = transforms.Compose([
    transforms.Resize((config.input_size, config.input_size)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

])

train_dir = "/content/flowers/flowers/train"
val_dir = "/content/flowers/flowers/val"

import zipfile
import os

zip_path = "/content/drive/MyDrive/flowers-20260820T043258Z-1-001.zip"
extract_path = "/content/flowers"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir(extract_path))

!find /content/flowers -maxdepth 3 -type d | head -50

train_dataset = datasets.ImageFolder(root=train_dir, transform=transform)
val_dataset = datasets.ImageFolder(root=val_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=config.batch_size)

import os

print(os.listdir("/content/drive/MyDrive"))

alexnet = models.alexnet(pretrained=config.pretrained)

# Freeze All Layers
for param in alexnet.parameters():
  param.requires_grad = False

# Replace final classifier Layer
alexnet.classifier[6] = nn.Linear(4096, 5)

# Only the new final Layer should be trainable
for param in alexnet.classifier[6].parameters():
  param.requires_grad = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
alexnet = alexnet.to(device)

# Watch the model's weights and gradients
wandb.watch(alexnet, log="all", log_freq=10)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(alexnet.parameters(), lr=config.learning_rate)



def train_model(model, criterion, optimizer, train_loader, val_loader, epochs = 10):
  for epoch in range(epochs):
    model.train()
    train_correct = 0
    train_total = 0
    running_loss = 0.0

    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-" * 30)

    for i, (images, labels) in enumerate(train_loader):
      images,labels = images.to(device), labels.to(device)

      optimizer.zero_grad()
      outputs = model(images)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()

      running_loss += loss.item()
      _, preds = torch.max(outputs, 1)
      batch_correct = (preds == labels).sum().item()
      train_correct += batch_correct
      train_total += labels.size(0)

      if (i + 1) % 10 == 0:
                batch_acc = batch_correct / labels.size(0)
                print(f"[Batch {i+1}/{len(train_loader)}] Loss: {loss.item():.4f}, Batch Acc: {batch_acc:.4f}")

    train_acc = train_correct / train_total
    wandb.log({"epoch": epoch + 1, "train_loss": running_loss, "train_accuracy": train_acc})
    print(f"Epoch {epoch+1} Summary - Loss: {running_loss:.4f}, Train Accuracy: {train_acc:.4f}")

    model.eval()
    val_correct = 0
    val_total = 0
    with torch.no_grad():
      for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, preds = torch.max(outputs, 1)
        val_correct += (preds == labels).sum().item()
        val_total += labels.size(0)

    val_acc = val_correct / val_total
    wandb.log({"epoch": epoch + 1, "val_accuracy": val_acc})
    print(f"Validation Accuracy: {val_acc:.4f}")

train_model(alexnet, criterion, optimizer, train_loader, val_loader, epochs=config.epochs)
