# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2CgBT7cnXOLxLsmVNx_39Civ9ZwKZzR
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle(1).json ~/.kaggle/

!kaggle datasets download -d jangedoo/utkface-new

import zipfile
zip = zipfile.ZipFile("/content/utkface-new.zip", 'r')
zip.extractall("/content")
zip.close()

import os
import numpy as p
import pandas as pd
from tensorflow.keras.preprocessing.image import ImageDataGenerator

folder_path = '/content/utkface_aligned_cropped/UTKFace'

age = []
gender = []
img_path = []
for file in os.listdir(folder_path):
  age.append(int(file.split('_')[0]))
  gender.append(int(file.split('_')[1]))
  img_path.append(file)

len(age)

df = pd.DataFrame({'age': age, 'gender': gender, 'img':img_path})

df.shape

df.head()

train_df = df.sample(frac=1, random_state=0).iloc[:20000]
test_df = df.sample(frac=1, random_state=0).iloc[20000:]

train_df.shape

test_df.shape

import tensorflow as tf

IMG_SIZE = (200, 200)
BATCH_SIZE = 64

def load_train_image(filename, age, gender):
    path = tf.strings.join([folder_path, "/", filename])

    image = tf.io.read_file(path)
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0

    # Augmentation
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_brightness(image, 0.1)
    image = tf.image.random_contrast(image, 0.8, 1.2)

    return image, {
        "age": tf.cast(age, tf.float32),
        "gender": tf.cast(gender, tf.float32)
    }


def load_test_image(filename, age, gender):
    path = tf.strings.join([folder_path, "/", filename])

    image = tf.io.read_file(path)
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0

    return image, {
        "age": tf.cast(age, tf.float32),
        "gender": tf.cast(gender, tf.float32)
    }


train_dataset = tf.data.Dataset.from_tensor_slices((
    train_df["img"].values,
    train_df["age"].values,
    train_df["gender"].values
))

train_dataset = train_dataset.map(
    load_train_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

train_dataset = (
    train_dataset
    .shuffle(1000)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)


test_dataset = tf.data.Dataset.from_tensor_slices((
    test_df["img"].values,
    test_df["age"].values,
    test_df["gender"].values
))

test_dataset = test_dataset.map(
    load_test_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

test_dataset = (
    test_dataset
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

from keras.applications.vgg16 import VGG16
from keras.layers import *
from keras.models import Model

vggnet = VGG16(include_top=False, input_shape=(200,200,3))

vggnet.trainable = False

output = vggnet.layers[-1].output

flatten = Flatten()(output)

# Age branch
dense1 = Dense(512, activation='relu')(flatten)
dense3 = Dense(512, activation='relu')(dense1)

# Gender branch
dense2 = Dense(512, activation='relu')(flatten)
dense4 = Dense(512, activation='relu')(dense2)

# Final outputs
output1 = Dense(1, activation='linear', name='age')(dense3)
output2 = Dense(1, activation='sigmoid', name='gender')(dense4)

model = Model(
    inputs=vggnet.input,
    outputs=[output1, output2]
)

model.summary()

from keras.utils import plot_model
plot_model(model)

model.compile(
    optimizer='adam',
    loss={
        'age': 'mae',
        'gender': 'binary_crossentropy'
    },
    metrics={
        'age': 'mae',
        'gender': 'accuracy'
    },
    loss_weights={
        'age': 1,
        'gender': 99
    }
)

history = model.fit(
    train_dataset,
    epochs=10,
    validation_data=test_dataset
)
