# -*- coding: utf-8 -*-
"""LeNet-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NroF9gprDQQ9d73pk5f0C8v88l-QthAp
"""

import tensorflow
import numpy as np
from tensorflow import keras
from keras.layers import Dense, Flatten, Conv2D, AveragePooling2D
from keras import Sequential
from keras.datasets import mnist
import matplotlib.pyplot as plt

(X_train, y_train), (X_test, y_test) = mnist.load_data()

print(X_train.shape)

X_train = np.pad(X_train, ((0,0), (2,2), (2,2)), mode='constant')
X_test = np.pad(X_test, ((0,0), (2,2), (2,2)), mode = 'constant')
print(X_train.shape)

"""LeNet Architecture"""

model = Sequential()

model.add(Conv2D(6, kernel_size = (5,5), padding = 'valid', activation = 'tanh', input_shape = (32,32,1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = 2, padding = 'valid'))

model.add(Conv2D(16, kernel_size = (5,5), padding = 'valid', activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2,2), strides = 2, padding = 'valid'))

model.add(Flatten())

model.add(Dense(120, activation = 'tanh'))
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(10, activation = 'softmax'))

model.summary()

plt.figure(figsize = (10,4))
for i in range(10):
  plt.subplot(2, 5, i + 1)
  plt.imshow(X_train[i], cmap = 'gray')
  plt.title(f"Label: {y_train[i]}")
  plt.axis('off')
plt.show()

X_train_main = X_train[:50000]
y_train_main = y_train[:50000]

x_val = X_train[50000:]
y_val = y_train[50000:]

X_train_main = X_train_main / 255.0
x_val = x_val / 255.0
X_test = X_test / 255.0

#Re-Shape data

X_train_main = X_train_main.reshape(50000, 32, 32, 1)
x_val = x_val.reshape(10000, 32, 32, 1)
X_test = X_test.reshape(10000, 32, 32, 1)

#One Hot Encoding of the output values

y_train_main = keras.utils.to_categorical(y_train_main, 10)
y_val = keras.utils.to_categorical(y_val, 10)
y_test = keras.utils.to_categorical(y_test, 10)

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

model. fit(X_train_main, y_train_main, epochs = 10, batch_size = 128, validation_data = (x_val, y_val))

test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)
